// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rqZ9PD2umVe7Ek4piJQ68WprlApP-rU',
    appId: '1:262754986573:web:0965954cc6e0f2e36e4a04',
    messagingSenderId: '262754986573',
    projectId: 'food-delivery-app-a5e49',
    authDomain: 'food-delivery-app-a5e49.firebaseapp.com',
    storageBucket: 'food-delivery-app-a5e49.appspot.com',
    measurementId: 'G-K9VERJND88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiuIpVP3RzvWaJc-IDkeX1oS8AlPzCnN0',
    appId: '1:262754986573:android:ef81c69dedf091d06e4a04',
    messagingSenderId: '262754986573',
    projectId: 'food-delivery-app-a5e49',
    storageBucket: 'food-delivery-app-a5e49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAfR42n7CPnvtEchUF-1TNdnvcmfbty0',
    appId: '1:262754986573:ios:0a9b1a59ce422efe6e4a04',
    messagingSenderId: '262754986573',
    projectId: 'food-delivery-app-a5e49',
    storageBucket: 'food-delivery-app-a5e49.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiAfR42n7CPnvtEchUF-1TNdnvcmfbty0',
    appId: '1:262754986573:ios:6c4e7f5f2c1c38576e4a04',
    messagingSenderId: '262754986573',
    projectId: 'food-delivery-app-a5e49',
    storageBucket: 'food-delivery-app-a5e49.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
